#!/bin/bash
sbatch run_3D_darwin_post_process.sbatch run_3P1V1Z_3D_param_virus_shunt-100 *your_date* virus_shunt-100
sbatch run_3D_darwin_post_process.sbatch run_3P1V1Z_3D_param_virus_shunt-90 *your_date* virus_shunt-90
sbatch run_3D_darwin_post_process.sbatch run_3P1V1Z_3D_param_virus_shunt-75 *your_date* virus_shunt-75
sbatch run_3D_darwin_post_process.sbatch run_3P1V1Z_3D_param_virus_shunt-60 *your_date* virus_shunt-60
sbatch run_3D_darwin_post_process.sbatch run_3P1V1Z_3D_param_virus_shunt-50 *your_date* virus_shunt-50
sbatch run_3D_darwin_post_process.sbatch run_3P1V1Z_3D_param_virus_shunt-25 *your_date* virus_shunt-25
sbatch run_3D_darwin_post_process.sbatch run_3P1V1Z_3D_param_virus_shunt-0 *your_date* virus_shunt-0

sbatch run_3D_darwin_post_process.sbatch run_3P1V1Z_3D_param_no_virus *your_date* no_virus

sbatch run_3D_darwin_post_process.sbatch run_3P1V1Z_3D_param_virus_shunt-100_no_I *your_date* virus_shunt-100_no_I
sbatch run_3D_darwin_post_process.sbatch run_3P1V1Z_3D_param_virus_shunt-100_I_growth *your_date* virus_shunt-100_I_growth

sbatch run_3D_darwin_post_process.sbatch run_3P1V1Z_3D_param_virus_shunt-100_no_DON_transport *your_date* virus_shunt-100_no_DON_transport
